### ISSUE TITLE
[BUG] Get ArrowInvalid on what should be a valid GeoJSON file

### ISSUE THREAD

**Issue by batpad** [developmentseed/lonboard#390]
## Context

Trying out the new CLI functionality, I tried to run `python -m lonboard Utah.geojson` to generate an HTML file for the dataset.

GeoJSON file I used is here (zipped): https://hostb.org/21GH

## Resulting behaviour, error message or logs

Got this error:

```
python -m lonboard Utah.geojson
/Users/sanjay/seed/lonboard/lonboard/_geoarrow/ops/reproject.py:81: UserWarning: Input being reprojected to EPSG:4326 CRS
  warnings.warn("Input being reprojected to EPSG:4326 CRS")
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/sanjay/seed/lonboard/lonboard/__main__.py", line 3, in <module>
    main()
  File "/Users/sanjay/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/sanjay/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/seed/lonboard/lonboard/_cli.py", line 129, in main
    map_ = viz(tables)
           ^^^^^^^^^^^
  File "/Users/sanjay/seed/lonboard/lonboard/_viz.py", line 117, in viz
    layers = [
             ^
  File "/Users/sanjay/seed/lonboard/lonboard/_viz.py", line 118, in <listcomp>
    create_layer_from_data_input(
  File "/Users/sanjay/seed/lonboard/lonboard/_viz.py", line 150, in create_layer_from_data_input
    return _viz_geoarrow_table(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/seed/lonboard/lonboard/_viz.py", line 318, in _viz_geoarrow_table
    return SolidPolygonLayer(table=table, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/seed/lonboard/lonboard/_layer.py", line 246, in __init__
    table = reproject_table(table, to_crs=OGC_84)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/seed/lonboard/lonboard/_geoarrow/ops/reproject.py", line 49, in reproject_table
    new_field, new_column = reproject_column(
                            ^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/seed/lonboard/lonboard/_geoarrow/ops/reproject.py", line 92, in reproject_column
    new_chunked_array = _reproject_column(
                        ^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/seed/lonboard/lonboard/_geoarrow/ops/reproject.py", line 124, in _reproject_column
    return pa.chunked_array(executor.map(func, column.chunks))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 1380, in pyarrow.lib.chunked_array
  File "/Users/sanjay/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/sanjay/.pyenv/versions/3.11.4/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/seed/lonboard/lonboard/_geoarrow/ops/reproject.py", line 162, in _reproject_chunk_nest_2
    return _map_coords_nest_2(arr, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanjay/seed/lonboard/lonboard/_geoarrow/ops/reproject.py", line 197, in _map_coords_nest_2
    new_ring_array = pa.ListArray.from_arrays(ring_offsets, new_coords)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/array.pxi", line 2219, in pyarrow.lib.ListArray.from_arrays
  File "pyarrow/array.pxi", line 1634, in pyarrow.lib.Array.validate
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: First or last list offset out of bounds
```

## Environment

- OS: MacOS 13.4.1
- Browser: [e.g. Chrome, Safari]
- Lonboard Version: 0.6.0 (latest `main` built locally)

## Steps to reproduce the bug

 - Download and unzip GeoJSON file from https://hostb.org/21GH
 - Run `python -m lonboard Utah.geojson`

Expected: An HTML file created with the dataset an opened in a browser

Actual: Get the error posted above

cc @kylebarron

**Comment by kylebarron** [comment]
Fixed over https://github.com/developmentseed/lonboard/pull/391 and https://github.com/developmentseed/lonboard/pull/393, and https://github.com/developmentseed/lonboard/pull/392 is a perf improvement that I discovered while looking into this.
